### ISSUE TITLE
Uncomplete list of items

### ISSUE THREAD

**Issue by Neukiru** [maximumstock/poe-currency-flip-planner#323]

**Comment by Neukiru** [comment]
Apparently the items are missing from the config list. Only handful of items are searched for, is it a bug? For instance, could not search for exalted orb conversions or scarabs and etc

**Comment by maximumstock** [comment]
I looked into this and I think the reason for the lack of conversions starting with `Exalted Orb`s is that there aren't any profitable ones (that the tool can find).

The list of paths the tool evaluates that is defined in `config/config.default.json` which is used if you don't configure anything yourself was data mined quite a while ago and is probably missing some commonly traded crafting items. If you want the tool to evaluate these items as well, feel free to create your custom config file and add a section like this and add all the items you want to sell that new item for:

```json
  "trading": {
    "<new item>": {
      "sell_for": {
        "Aetheric Fossil": null,
        "Awakened Sextant": null,
        "Blessed Orb": null,
        "Cartographer's Chisel": null,
        "Chromatic Orb": null,
        "Divine Orb": null,
        "Gemcutter's Prism": null,
        "Gilded Divination Scarab": null,
        "Jagged Fossil": null,
        "Jeweller's Orb": null,
        "Orb of Alchemy": null,
        "Orb of Alteration": null,
        "Orb of Chance": null,
        "Orb of Fusing": null,
        "Orb of Regret": null,
        "Orb of Scouring": null,
        "Potent Chaotic Resonator": null,
        "Regal Orb": null,
        "Serrated Fossil": null,
        "Shuddering Fossil": null,
        "Simple Sextant": null,
        "Vaal Orb": null
      }
    },
```

Generally speaking, this tool is not really useful at the moment. The sheer amount of price-fixing offers needs to be filtered out first to make any of this graph evaluation to be meaningful. I haven't found a way to dynamically filter them out successfully, which I think is a hard task, since the conversion rate distributions are uniquely skewed for all different item combinations. I might sit down some time this week and implement a simple rule based filter that at least takes care of the main trading paths around `Chaos Orb`s so that the tool safely detects `100 Chaos for 50 Jeweller's` as crap.
