### ISSUE TITLE
Look into built distributions

### ISSUE THREAD

**Issue by maximumstock** [maximumstock/poe-currency-flip-planner#67]
Having to install pipenv and all deps is cumbersome, look into https://docs.python.org/3/distutils/builtdist.html

**Comment by giorgiovilardo** [comment]
something easier (patchy/hacky maybe?) would be to include a simple requirements.txt.

I was a happy pipenv user, before it started breaking hard (losing python paths, losing venvs, etc) every update. the magic stopped quickly.

Now I prefer to work with the simple combo venv+pip, which breaks way less (even if it is way less flexible). If I need some particular py version I'd rather spin up a server or a container rather than mess again with pipenv, but this is my personal beef.

Including a requirements.txt could ease the installation process easily, with a suggestione like

```
# Install

1. python3 -m venv env
2. pip install -r requirements.txt
```

**Comment by maximumstock** [comment]
I'm not entirely happy with pipenv either, and I most certainly comprehend your pain points. I guess for most users with a simple Python 3 installation your ways is easier and less clunky, so I'll add a section in the docs. Thanks for reaching out!

**Comment by maximumstock** [comment]
Added in https://github.com/maximumstock/poe-currency-flip-planner/commit/951b274fd147c07ff2c08b9b3fe86ebb575c5a1c
